language: python
python:
  - "3.6"
cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"
before_install: pip install poetry
install:
  - make
env:
  - FLASK_APP=autoapp.py
script:
  - make check
after_success:
  - coveralls
