[tool.black]
include = '\.py$'
# Don't attempt to normalize strings
skip-string-normalization = true

[tool.isort]
line_length = 88
known_first_party = "member"
multi_line_output = 3
include_trailing_comma = true
